services:
  - type: web
    name: team-22-front
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run preview
    envVars:
      - key: NODE_VERSION
        value: 20.16.0