export const COUNTRY_TIMEZONES = {
  'Afganistán': 'Asia/Kabul',
  'Albania': 'Europe/Tirane',
  'Alemania': 'Europe/Berlin',
  'Andorra': 'Europe/Andorra',
  'Angola': 'Africa/Luanda',
  'Antigua y Barbuda': 'America/Antigua',
  'Arabia Saudita': 'Asia/Riyadh',
  'Argelia': 'Africa/Algiers',
  'Argentina': 'America/Argentina/Buenos_Aires',
  'Armenia': 'Asia/Yerevan',
  'Australia': 'Australia/Sydney',
  'Austria': 'Europe/Vienna',
  'Azerbaiyán': 'Asia/Baku',
  'Bahamas': 'America/Nassau',
  'Bangladés': 'Asia/Dhaka',
  'Barbados': 'America/Barbados',
  'Baréin': 'Asia/Bahrain',
  'Bélgica': 'Europe/Brussels',
  'Belice': 'America/Belize',
  'Benín': 'Africa/Porto-Novo',
  'Bielorrusia': 'Europe/Minsk',
  'Birmania': 'Asia/Yangon',
  'Bolivia': 'America/La_Paz',
  'Bosnia y Herzegovina': 'Europe/Sarajevo',
  'Botsuana': 'Africa/Gaborone',
  'Brasil': 'America/Sao_Paulo',
  'Brunéi': 'Asia/Brunei',
  'Bulgaria': 'Europe/Sofia',
  'Burkina Faso': 'Africa/Ouagadougou',
  'Burundi': 'Africa/Bujumbura',
  'Bután': 'Asia/Thimphu',
  'Cabo Verde': 'Atlantic/Cape_Verde',
  'Camboya': 'Asia/Phnom_Penh',
  'Camerún': 'Africa/Douala',
  'Canadá': 'America/Toronto',
  'Catar': 'Asia/Qatar',
  'Chad': 'Africa/Ndjamena',
  'Chile': 'America/Santiago',
  'China': 'Asia/Shanghai',
  'Chipre': 'Asia/Nicosia',
  'Ciudad del Vaticano': 'Europe/Vatican',
  'Colombia': 'America/Bogota',
  'Comoras': 'Indian/Comoro',
  'Corea del Norte': 'Asia/Pyongyang',
  'Corea del Sur': 'Asia/Seoul',
  'Costa de Marfil': 'Africa/Abidjan',
  'Costa Rica': 'America/Costa_Rica',
  'Croacia': 'Europe/Zagreb',
  'Cuba': 'America/Havana',
  'Dinamarca': 'Europe/Copenhagen',
  'Dominica': 'America/Dominica',
  'Ecuador': 'America/Guayaquil',
  'Egipto': 'Africa/Cairo',
  'El Salvador': 'America/El_Salvador',
  'Emiratos Árabes Unidos': 'Asia/Dubai',
  'Eritrea': 'Africa/Asmara',
  'Eslovaquia': 'Europe/Bratislava',
  'Eslovenia': 'Europe/Ljubljana',
  'España': 'Europe/Madrid',
  'Estados Unidos': 'America/New_York',
  'Estonia': 'Europe/Tallinn',
  'Etiopía': 'Africa/Addis_Ababa',
  'Filipinas': 'Asia/Manila',
  'Finlandia': 'Europe/Helsinki',
  'Fiyi': 'Pacific/Fiji',
  'Francia': 'Europe/Paris',
  'Gabón': 'Africa/Libreville',
  'Gambia': 'Africa/Banjul',
  'Georgia': 'Asia/Tbilisi',
  'Ghana': 'Africa/Accra',
  'Granada': 'America/Grenada',
  'Grecia': 'Europe/Athens',
  'Guatemala': 'America/Guatemala',
  'Guyana': 'America/Guyana',
  'Guinea': 'Africa/Conakry',
  'Guinea ecuatorial': 'Africa/Malabo',
  'Guinea-Bisáu': 'Africa/Bissau',
  'Haití': 'America/Port-au-Prince',
  'Honduras': 'America/Tegucigalpa',
  'Hungría': 'Europe/Budapest',
  'India': 'Asia/Kolkata',
  'Indonesia': 'Asia/Jakarta',
  'Irak': 'Asia/Baghdad',
  'Irán': 'Asia/Tehran',
  'Irlanda': 'Europe/Dublin',
  'Islandia': 'Atlantic/Reykjavik',
  'Islas Marshall': 'Pacific/Majuro',
  'Islas Salomón': 'Pacific/Guadalcanal',
  'Israel': 'Asia/Jerusalem',
  'Italia': 'Europe/Rome',
  'Jamaica': 'America/Jamaica',
  'Japón': 'Asia/Tokyo',
  'Jordania': 'Asia/Amman',
  'Kazajistán': 'Asia/Almaty',
  'Kenia': 'Africa/Nairobi',
  'Kirguistán': 'Asia/Bishkek',
  'Kiribati': 'Pacific/Tarawa',
  'Kuwait': 'Asia/Kuwait',
  'Laos': 'Asia/Vientiane',
  'Lesoto': 'Africa/Maseru',
  'Letonia': 'Europe/Riga',
  'Líbano': 'Asia/Beirut',
  'Liberia': 'Africa/Monrovia',
  'Libia': 'Africa/Tripoli',
  'Liechtenstein': 'Europe/Vaduz',
  'Lituania': 'Europe/Vilnius',
  'Luxemburgo': 'Europe/Luxembourg',
  'Macedonia del Norte': 'Europe/Skopje',
  'Madagascar': 'Indian/Antananarivo',
  'Malasia': 'Asia/Kuala_Lumpur',
  'Malaui': 'Africa/Blantyre',
  'Maldivas': 'Indian/Maldives',
  'Malta': 'Europe/Malta',
  'Marruecos': 'Africa/Casablanca',
  'Mauricio': 'Indian/Mauritius',
  'Mauritania': 'Africa/Nouakchott',
  'México': 'America/Mexico_City',
  'Micronesia': 'Pacific/Chuuk',
  'Moldavia': 'Europe/Chisinau',
  'Mónaco': 'Europe/Monaco',
  'Mongolia': 'Asia/Ulaanbaatar',
  'Montenegro': 'Europe/Podgorica',
  'Mozambique': 'Africa/Maputo',
  'Namibia': 'Africa/Windhoek',
  'Nauru': 'Pacific/Nauru',
  'Nepal': 'Asia/Kathmandu',
  'Nicaragua': 'America/Managua',
  'Níger': 'Africa/Niamey',
  'Nigeria': 'Africa/Lagos',
  'Noruega': 'Europe/Oslo',
  'Nueva Zelanda': 'Pacific/Auckland',
  'Omán': 'Asia/Muscat',
  'Países Bajos': 'Europe/Amsterdam',
  'Pakistán': 'Asia/Karachi',
  'Palaos': 'Pacific/Palau',
  'Panamá': 'America/Panama',
  'Papúa Nueva Guinea': 'Pacific/Port_Moresby',
  'Paraguay': 'America/Asuncion',
  'Perú': 'America/Lima',
  'Polonia': 'Europe/Warsaw',
  'Portugal': 'Europe/Lisbon',
  'Reino Unido': 'Europe/London',
  'República Centroafricana': 'Africa/Bangui',
  'República Checa': 'Europe/Prague',
  'República del Congo': 'Africa/Brazzaville',
  'República Democrática del Congo': 'Africa/Kinshasa',
  'República Dominicana': 'America/Santo_Domingo',
  'Ruanda': 'Africa/Kigali',
  'Rumanía': 'Europe/Bucharest',
  'Rusia': 'Europe/Moscow',
  'Samoa': 'Pacific/Apia',
  'San Cristóbal y Nieves': 'America/St_Kitts',
  'San Marino': 'Europe/San_Marino',
  'San Vicente y las Granadinas': 'America/St_Vincent',
  'Santa Lucía': 'America/St_Lucia',
  'Santo Tomé y Príncipe': 'Africa/Sao_Tome',
  'Senegal': 'Africa/Dakar',
  'Serbia': 'Europe/Belgrade',
  'Seychelles': 'Indian/Mahe',
  'Sierra Leona': 'Africa/Freetown',
  'Singapur': 'Asia/Singapore',
  'Siria': 'Asia/Damascus',
  'Somalia': 'Africa/Mogadishu',
  'Sri Lanka': 'Asia/Colombo',
  'Suazilandia': 'Africa/Mbabane',
  'Sudáfrica': 'Africa/Johannesburg',
  'Sudán': 'Africa/Khartoum',
  'Sudán del Sur': 'Africa/Juba',
  'Suecia': 'Europe/Stockholm',
  'Suiza': 'Europe/Zurich',
  'Surinam': 'America/Paramaribo',
  'Tailandia': 'Asia/Bangkok',
  'Tanzania': 'Africa/Dar_es_Salaam',
  'Tayikistán': 'Asia/Dushanbe',
  'Timor Oriental': 'Asia/Dili',
  'Togo': 'Africa/Lome',
  'Tonga': 'Pacific/Tongatapu',
  'Trinidad y Tobago': 'America/Port_of_Spain',
  'Túnez': 'Africa/Tunis',
  'Turkmenistán': 'Asia/Ashgabat',
  'Turquía': 'Europe/Istanbul',
  'Tuvalu': 'Pacific/Funafuti',
  'Ucrania': 'Europe/Kiev',
  'Uganda': 'Africa/Kampala',
  'Uruguay': 'America/Montevideo',
  'Uzbekistán': 'Asia/Tashkent',
  'Vanuatu': 'Pacific/Efate',
  'Venezuela': 'America/Caracas',
  'Vietnam': 'Asia/Ho_Chi_Minh',
  'Yemen': 'Asia/Aden',
  'Yibuti': 'Africa/Djibouti',
  'Zambia': 'Africa/Lusaka',
  'Zimbabue': 'Africa/Harare'
};
